/**
 * @file grid_mode.c
 * @author Deepak
 * @brief Grid connected mode implimentation.
 * @version 0.1
 * @date 2021-07-11
 * 
 * @copyright Copyright (c) 2021
 * 
 */
#include"hmgbpvs.h"

// In this mode of operation power generated by pv is zero and battery is discharged.
// So, the full load deaman will be fulfilled by grid.

// grid power must be greater than 2000 w.

int grid_mode(float power_g, int load)
{
      printf("Dear user according to your input, currently Grid connected mode is operating.\n");
      int pow_ext = power_g -load;
      return pow_ext;
}